name: 部署到测试环境

on:
  push:
    branches: [test]
    paths:
      - 'apps/api/**'
      - 'packages/shared/**'
      - '.github/workflows/deploy-test.yml'
  workflow_dispatch:

jobs:
  deploy-test:
    name: 部署到测试环境
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 设置PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 安装依赖
        run: pnpm install --no-frozen-lockfile

      - name: 构建shared包
        run: cd packages/shared && pnpm build

      - name: 构建API包
        run: cd apps/api && pnpm build

      - name: 配置AWS凭证
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1

      - name: 部署到AWS Lambda测试环境
        run: cd apps/api && pnpm run deploy:lambda:test
        env:
          MONGODB_URI_test: ${{ secrets.MONGODB_URI_TEST }}
          JWT_SECRET_test: ${{ secrets.JWT_SECRET_TEST }}
          CORS_ORIGINS_test: ${{ secrets.CORS_ORIGINS_TEST }}
          ADMIN_SECRET_test: ${{ secrets.ADMIN_SECRET_TEST }}
