name: 版本发布

on:
  push:
    branches:
      - release
    paths:
      - 'packages/**'
      - 'apps/api/**' # 添加API路径监听
  workflow_dispatch:
    inputs:
      release_type:
        description: '发布类型'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: 创建发布
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          # 获取完整Git历史以便Changesets可以生成正确的变更日志
          fetch-depth: 0

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: 设置PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 安装依赖
        run: pnpm install

      - name: 更新版本
        id: update-version
        run: |
          RELEASE_TYPE="${{ github.event.inputs.release_type || 'patch' }}"
          echo "正在使用 $RELEASE_TYPE 更新版本..."
          pnpm version $RELEASE_TYPE --no-git-tag-version
          # 将新版本保存到输出变量
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 构建包
        run: pnpm build

      - name: 创建变更日志
        run: |
          echo "## 变更内容" > CHANGELOG.md
          git log -10 --pretty=format:"- %s" >> CHANGELOG.md

      - name: 创建Git标签
        run: |
          VERSION="${{ steps.update-version.outputs.version }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: 发布 v$VERSION"
          git tag -a "v$VERSION" -m "版本 $VERSION"
          git push origin "v$VERSION"

      - name: 创建GitHub发布
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PROD_GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.update-version.outputs.version }}
          release_name: 版本 ${{ steps.update-version.outputs.version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

  deploy-lambda:
    name: 部署Lambda函数
    needs: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release' # 仅在release分支执行
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: 设置PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 安装依赖
        run: pnpm install

      - name: 构建API
        run: pnpm --filter api build

      - name: 配置AWS凭证
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1 # 使用您的AWS区域

      - name: 创建部署包
        run: |
          cd apps/api/dist
          zip -r ../deployment.zip .
          cd ..
          # 如果需要包含node_modules
          zip -r deployment.zip node_modules

      - name: 部署到Lambda
        run: |
          aws lambda update-function-code \
            --function-name shopping-api \
            --zip-file fileb://apps/api/deployment.zip \
            --publish

      - name: 清理部署工件
        run: rm -f apps/api/deployment.zip
